// ARM SMMU v3 Conformance Gap Tests: confGaps17Mar2026_9pm.md + QA audit NEW-GAP-I
//
// NEW-GAP-A: GATOS_PAR REASON field 4-value encoding (§9.1.4)
// NEW-GAP-B: F_VMS_FETCH FAULTCODE=0x25 (very low, code-fix only — never generated by SW model)
// NEW-GAP-C: AxPROT[1] privilege from typed AccessType variants (§3.6/§13.1, C++ only)
// NEW-GAP-I: GATOS_PAR FADDR[55:12] populated with faulting IPA on stage-2 fault (§9.1.4)

#include <gtest/gtest.h>
#include "smmu/smmu.h"
#include "smmu/types.h"
#include "smmu/address_space.h"
#include "smmu/configuration.h"
#include <memory>

using namespace smmu;

namespace {

static constexpr StreamID SID  = 0xA0;
static constexpr PASID    PID  = 0;

// Extract REASON bits[2:1] from a GATOS_PAR fault value.
inline uint64_t extractReason(uint64_t par) {
    return (par >> 1) & 0x3u;
}

// Extract FAULTCODE bits[11:4] from a GATOS_PAR fault value.
inline uint64_t extractFaultCode(uint64_t par) {
    return (par >> 4) & 0xFFu;
}

void enableSmmu(SMMU& s) {
    s.enable();
    s.setCR0(s.getCR0() | SMMU::CR0_EVENTQEN);
}

// Configure a basic stage-1-only stream (no PASID table).
void setupStage1Stream(SMMU& smmu, StreamID sid, PASID pasid) {
    StreamConfig cfg;
    cfg.translationEnabled = true;
    cfg.stage1Enabled      = true;
    cfg.stage2Enabled      = false;
    cfg.faultMode          = FaultMode::Terminate;
    cfg.t0sz               = 0; // no VA range restriction
    ASSERT_TRUE(smmu.configureStream(sid, cfg).isOk());
    ASSERT_TRUE(smmu.enableStream(sid).isOk());
    ASSERT_TRUE(smmu.createStreamPASID(sid, pasid).isOk());
}

// Configure a two-stage stream with a dedicated stage-2 address space.
// Stage-1 translates IOVA → IPA; stage-2 is created but has NO mappings.
// Calling translate on an IOVA that has a stage-1 mapping will yield a
// stage-2 IPA fault (F_TRANSLATION, s2=true, eventClass=IN=2 → REASON=0b11).
void setupTwoStageStream(SMMU& smmu, StreamID sid, PASID pasid,
                         std::shared_ptr<AddressSpace>& stage2AS) {
    StreamConfig cfg;
    cfg.translationEnabled = true;
    cfg.stage1Enabled      = true;
    cfg.stage2Enabled      = true;
    cfg.faultMode          = FaultMode::Terminate;
    cfg.t0sz               = 0;  // no VA range restriction
    cfg.s2t0sz             = 0;  // no IPA range restriction
    cfg.s2ps               = 5;  // 48-bit S2PS
    ASSERT_TRUE(smmu.configureStream(sid, cfg).isOk());
    ASSERT_TRUE(smmu.enableStream(sid).isOk());
    ASSERT_TRUE(smmu.createStreamPASID(sid, pasid).isOk());

    // Create a fresh (empty) stage-2 address space — no IPA mappings.
    stage2AS = std::make_shared<AddressSpace>();
    ASSERT_TRUE(smmu.setStreamStage2AddressSpace(sid, stage2AS).isOk());
}

// Map a single stage-1 page IOVA → PA (used as IPA for two-stage).
void mapStage1Page(SMMU& smmu, StreamID sid, PASID pasid,
                   IOVA iova, PA pa) {
    PagePermissions perms;
    perms.read  = true;
    perms.write = true;
    perms.execute = false;
    ASSERT_TRUE(smmu.mapPage(sid, pasid, iova, pa, perms).isOk());
}

} // anonymous namespace

// =============================================================================
// NEW-GAP-A: GATOS_PAR REASON field must encode 4 distinct values (§9.1.4)
//
// §9.1.4 REASON encoding:
//   0b00 = stage-1 / config fault  (s2=false)
//   0b01 = stage-2 during CD fetch (s2=true, eventClass=0 CD)
//   0b10 = stage-2 during TT walk  (s2=true, eventClass=1 TTD)
//   0b11 = stage-2 on IPA input    (s2=true, eventClass=2 IN)
//
// The SW model only generates eventClass=2 (IN) for F_TRANSLATION events.
// A stage-2 IPA fault (unmapped IPA) gives s2=true, eventClass=2 → REASON=0b11.
//
// BEFORE FIX: reason = (s2 ? 1 : 0) — always 0b01 for any stage-2 fault.
// AFTER FIX:  reason = (s2 ? eventClass+1 : 0) — 0b11 for IN-class stage-2 fault.
// =============================================================================

// NEW-GAP-A Test 1: Stage-1-only translation fault → REASON=0b00
// This is a baseline regression guard; it should pass before and after the fix.
TEST(GapsConfGaps17Mar2026, new_gap_a_stage1_fault_reason_is_0b00) {
    SMMU smmu;
    enableSmmu(smmu);
    static constexpr StreamID S = SID;

    setupStage1Stream(smmu, S, PID);
    // No stage-1 mapping → F_TRANSLATION, s2=false → REASON=0b00

    static constexpr IOVA UNMAPPED_IOVA = 0x5000ULL;
    uint64_t par = smmu.gatosTranslate(S, PID, UNMAPPED_IOVA, AccessType::Read);

    EXPECT_EQ(par & 0x1u, 1u) << "bit 0 must be 1 (FAULT)";
    uint64_t reason = extractReason(par);
    EXPECT_EQ(reason, 0u)
        << "NEW-GAP-A: stage-1 fault must produce REASON=0b00; got 0b"
        << reason;
}

// NEW-GAP-A Test 2: Stage-2 IPA fault (unmapped IPA) → REASON=0b11
// Stage-1 maps IOVA→IPA, but stage-2 has no IPA mapping.
// The fault is F_TRANSLATION with s2=true, eventClass=2 (IN).
// REASON = eventClass + 1 = 2 + 1 = 3 = 0b11.
//
// BEFORE FIX: REASON=1 (0b01) — wrong, uses s2?1:0.
// AFTER FIX:  REASON=3 (0b11) — correct, uses s2?(eventClass+1):0.
TEST(GapsConfGaps17Mar2026, new_gap_a_stage2_ipa_fault_reason_is_0b11) {
    SMMU smmu;
    enableSmmu(smmu);
    static constexpr StreamID S = SID + 1u;

    std::shared_ptr<AddressSpace> s2as;
    setupTwoStageStream(smmu, S, PID, s2as);

    // Map stage-1 IOVA → IPA (IPA has no stage-2 mapping → stage-2 fault).
    static constexpr IOVA IOVA_VAL = 0x1000ULL;
    static constexpr PA   IPA_VAL  = 0x8000'0000ULL;
    mapStage1Page(smmu, S, PID, IOVA_VAL, IPA_VAL);

    // gatosTranslate: stage-1 succeeds (IPA_VAL), stage-2 fails (unmapped) → FAULT=1
    uint64_t par = smmu.gatosTranslate(S, PID, IOVA_VAL, AccessType::Read);

    EXPECT_EQ(par & 0x1u, 1u) << "bit 0 must be 1 (FAULT)";
    uint64_t reason = extractReason(par);
    EXPECT_EQ(reason, 3u)
        << "NEW-GAP-A: stage-2 IPA fault (IN class) must produce REASON=0b11 (3); "
        << "got 0b" << reason << ". Before fix this was 0b01 (s2?1:0).";
    EXPECT_EQ(extractFaultCode(par), 0x10u)
        << "FAULTCODE must be 0x10 (F_TRANSLATION) for unmapped IPA";
}

// =============================================================================
// NEW-GAP-C: AxPROT[1] privilege derivation from typed AccessType (§3.6/§13.1)
//
// C++ currently ignores AccessType in determinePrivilegeLevel() and always
// returns EL0 for NonSecure/Secure streams regardless of the access type.
// This means *Privileged AccessType variants are silently demoted to EL0 in
// the FaultSyndrome.privilegeLevel field.
//
// FIX: For Secure/NonSecure, check accessType:
//   *Privileged variants (ReadPrivileged, WritePrivileged, etc.) → EL1
//   unprivileged variants (Read, Write, Execute, etc.)           → EL0
//
// Root  → EL3 (unchanged)
// Realm → EL2 (unchanged)
//
// Observable through FaultRecord.syndrome.privilegeLevel when a two-stage fault
// is generated (recordComprehensiveFault path uses determinePrivilegeLevel).
//
// BEFORE FIX: ReadPrivileged → EL0 (wrong).
// AFTER FIX:  ReadPrivileged → EL1 (correct per §13.1.3).
// =============================================================================

// NEW-GAP-C Test 1: ReadPrivileged access → FaultRecord.syndrome.privilegeLevel == EL1
//
// A two-stage stream where stage-2 has no IPA mapping.
// Translate with ReadPrivileged → stage-2 fault → recordComprehensiveFault
// → determinePrivilegeLevel(ReadPrivileged, NonSecure) should return EL1.
//
// BEFORE FIX: syndrome.privilegeLevel == EL0.
// AFTER FIX:  syndrome.privilegeLevel == EL1.
TEST(GapsConfGaps17Mar2026, new_gap_c_read_privileged_gives_el1_in_syndrome) {
    SMMU smmu;
    enableSmmu(smmu);
    static constexpr StreamID S = SID + 2u;

    std::shared_ptr<AddressSpace> s2as;
    setupTwoStageStream(smmu, S, PID, s2as);

    static constexpr IOVA IOVA_VAL = 0x2000ULL;
    static constexpr PA   IPA_VAL  = 0x9000'0000ULL;
    mapStage1Page(smmu, S, PID, IOVA_VAL, IPA_VAL);

    // Privileged read: AccessType::ReadPrivileged
    smmu.translate(S, PID, IOVA_VAL, AccessType::ReadPrivileged);

    auto events = smmu.getEvents();
    ASSERT_TRUE(events.isOk()) << "getEvents() must succeed";
    const auto& recs = events.getValue();
    ASSERT_FALSE(recs.empty()) << "Expected a FaultRecord for the stage-2 fault";

    // Find the stage-2 translation fault record (most recent entry).
    const FaultRecord& rec = recs.back();
    EXPECT_EQ(rec.syndrome.privilegeLevel, PrivilegeLevel::EL1)
        << "NEW-GAP-C: ReadPrivileged on NonSecure stream must produce EL1 in "
        << "FaultSyndrome.privilegeLevel; got "
        << static_cast<int>(rec.syndrome.privilegeLevel)
        << ". Before fix this was EL0 because determinePrivilegeLevel ignored accessType.";
}

// NEW-GAP-C Test 2: unprivileged Read access → FaultRecord.syndrome.privilegeLevel == EL0
//
// Regression guard: an unprivileged read must still produce EL0.
// This should pass before and after the fix.
TEST(GapsConfGaps17Mar2026, new_gap_c_read_unprivileged_gives_el0_in_syndrome) {
    SMMU smmu;
    enableSmmu(smmu);
    static constexpr StreamID S = SID + 3u;

    std::shared_ptr<AddressSpace> s2as;
    setupTwoStageStream(smmu, S, PID, s2as);

    static constexpr IOVA IOVA_VAL = 0x3000ULL;
    static constexpr PA   IPA_VAL  = 0xA000'0000ULL;
    mapStage1Page(smmu, S, PID, IOVA_VAL, IPA_VAL);

    // Unprivileged read: AccessType::Read
    smmu.translate(S, PID, IOVA_VAL, AccessType::Read);

    auto events = smmu.getEvents();
    ASSERT_TRUE(events.isOk()) << "getEvents() must succeed";
    const auto& recs = events.getValue();
    ASSERT_FALSE(recs.empty()) << "Expected a FaultRecord for the stage-2 fault";

    const FaultRecord& rec = recs.back();
    EXPECT_EQ(rec.syndrome.privilegeLevel, PrivilegeLevel::EL0)
        << "NEW-GAP-C: unprivileged Read on NonSecure stream must produce EL0 in "
        << "FaultSyndrome.privilegeLevel; got "
        << static_cast<int>(rec.syndrome.privilegeLevel);
}

// =============================================================================
// NEW-GAP-I: GATOS_PAR FADDR[55:12] populated on stage-2 fault (§9.1.4)
//
// §9.1.4 Table (TYPE=0b11 stage-1-and-2, REASON=0b11 S2 IN):
//   FADDR = "IPA input to stage 2 (stage 1 output)"
//
// When a stage-2 IPA fault occurs (s2=true, REASON=0b11), GATOS_PAR bits[55:12]
// must contain the page-aligned IPA that was input to stage 2 (ev.ipa & ~0xFFF).
// For other REASON values (CD/TT fetches), FADDR also carries the respective IPA.
// For REASON=0b00 (stage-1 / config fault), FADDR must be 0.
//
// BEFORE FIX: GATOS_PAR = 0x1 | (reason<<1) | (faultCode<<4) — FADDR always 0.
// AFTER FIX:  GATOS_PAR |= (ipa & 0x00FFFFFFFFFFF000) when s2=true (REASON≠0).
// =============================================================================

// NEW-GAP-I Test 1: Stage-2 IPA fault → FADDR[55:12] = page-aligned IPA
//
// IPA_VAL = 0x8000_1000 → page-aligned = 0x8000_1000 (already 4K-aligned).
// GATOS_PAR bits[55:12] should equal 0x8000_1000.
//
// BEFORE FIX: FADDR=0.
// AFTER FIX:  FADDR=0x8000_1000 (bits[55:12] of the returned par value).
TEST(GapsConfGaps17Mar2026, new_gap_i_gatos_par_faddr_set_to_faulting_ipa) {
    SMMU smmu;
    enableSmmu(smmu);
    static constexpr StreamID S = SID + 4u;

    std::shared_ptr<AddressSpace> s2as;
    setupTwoStageStream(smmu, S, PID, s2as);

    // Stage-1 maps IOVA → IPA_VAL; stage-2 has no mapping for IPA_VAL.
    static constexpr IOVA IOVA_VAL = 0x4000ULL;
    static constexpr PA   IPA_VAL  = 0x8000'1000ULL; // page-aligned IPA
    mapStage1Page(smmu, S, PID, IOVA_VAL, IPA_VAL);

    uint64_t par = smmu.gatosTranslate(S, PID, IOVA_VAL, AccessType::Read);

    EXPECT_EQ(par & 0x1u, 1u) << "FAULT bit must be set";
    EXPECT_EQ(extractReason(par), 3u) << "REASON must be 0b11 (stage-2 IPA fault)";

    // Extract FADDR: bits[55:12] of par.
    uint64_t faddr = par & 0x00FFFFFFFFFFF000ULL;
    EXPECT_EQ(faddr, IPA_VAL)
        << "NEW-GAP-I: GATOS_PAR FADDR[55:12] must equal faulting IPA 0x"
        << std::hex << IPA_VAL << "; got 0x" << faddr
        << ". Before fix FADDR was always 0.";
}

// NEW-GAP-I Test 2: Stage-1-only fault → FADDR[55:12] must be 0
//
// When REASON=0b00 (stage-1 fault), FADDR must be 0 per §9.1.4 table.
// This is a regression guard: should pass before and after the fix.
TEST(GapsConfGaps17Mar2026, new_gap_i_gatos_par_faddr_zero_for_stage1_fault) {
    SMMU smmu;
    enableSmmu(smmu);
    static constexpr StreamID S = SID + 5u;

    setupStage1Stream(smmu, S, PID);
    // No page mapped → F_TRANSLATION, s2=false → REASON=0b00 → FADDR=0.
    uint64_t par = smmu.gatosTranslate(S, PID, 0x6000ULL, AccessType::Read);

    EXPECT_EQ(par & 0x1u, 1u) << "FAULT bit must be set";
    EXPECT_EQ(extractReason(par), 0u) << "REASON must be 0b00 for stage-1 fault";

    uint64_t faddr = par & 0x00FFFFFFFFFFF000ULL;
    EXPECT_EQ(faddr, 0u)
        << "NEW-GAP-I: FADDR must be 0 for stage-1 fault (REASON=0b00); got 0x"
        << std::hex << faddr;
}
