//! Tests for ARM SMMU v3 conformance gaps: confGaps17Mar2026_9pm.md + QA audit NEW-GAP-I
//!
//! - NEW-GAP-A: GATOS_PAR REASON field must encode 4 distinct values (§9.1.4)
//! - NEW-GAP-B: F_VMS_FETCH FAULTCODE=0x25 (Very Low — not generated by SW model, code-fix only)
//! - NEW-GAP-C: AxPROT[1] privilege derivation (C++ only — Rust uses typed AccessType)
//! - NEW-GAP-I: GATOS_PAR FADDR[55:12] populated with faulting IPA on stage-2 fault (§9.1.4)
#![allow(missing_docs)]
#![allow(clippy::doc_markdown)]

use smmu::types::{
    AccessType, FaultMode, PagePermissions, SecurityState, StreamConfig, StreamID, IOVA, PA, PASID,
};
use smmu::SMMU;

// ============================================================================
// Helpers
// ============================================================================

fn enable_smmu(smmu: &SMMU) {
    smmu.set_cr0(SMMU::CR0_SMMUEN | SMMU::CR0_EVENTQEN | SMMU::CR0_CMDQEN | SMMU::CR0_PRIQEN);
}

fn sid(id: u32) -> StreamID {
    StreamID::new(id).unwrap()
}

fn pasid(id: u32) -> PASID {
    PASID::new(id).unwrap()
}

fn iova(addr: u64) -> IOVA {
    IOVA::new(addr).unwrap()
}

fn pa(addr: u64) -> PA {
    PA::new(addr).unwrap()
}

/// Extract REASON from GATOS_PAR bits[2:1].
const fn extract_reason(par: u64) -> u64 {
    (par >> 1) & 0x3
}

/// Extract FAULTCODE from GATOS_PAR bits[11:4].
const fn extract_faultcode(par: u64) -> u64 {
    (par >> 4) & 0xFF
}

/// Set up a two-stage stream with an empty stage-2 address space (no IPA mappings).
/// Translating an IOVA that has a stage-1 mapping will produce a stage-2 IPA fault.
fn setup_two_stage_stream(smmu: &SMMU, stream_id: StreamID) {
    let cfg = StreamConfig::builder()
        .stage1_enabled(true)
        .stage2_enabled(true)
        .translation_enabled(true)
        .fault_mode(FaultMode::Terminate)
        .t0sz(0)      // no VA range restriction
        .s2_t0sz(16)  // minimum legal S2T0SZ per §5.2 (BUG-AUDIT-45 fix: 0 is out of range [16,39])
        .s2_ps(5)     // 48-bit S2PS
        .build()
        .unwrap();
    smmu.configure_stream(stream_id, cfg).unwrap();
    smmu.create_pasid(stream_id, pasid(0)).unwrap();
    smmu.create_stage2_address_space(stream_id).unwrap();
    // Stage-2 address space is empty: any IPA will be unmapped.
}

/// Map a stage-1 page IOVA → PA (used as IPA in two-stage translation).
fn map_stage1_page(smmu: &SMMU, stream_id: StreamID, iova_addr: u64, pa_addr: u64) {
    smmu.map_page(
        stream_id,
        pasid(0),
        iova(iova_addr),
        pa(pa_addr),
        PagePermissions::read_write(),
        SecurityState::NonSecure,
    )
    .unwrap();
}

// ============================================================================
// NEW-GAP-A: GATOS_PAR REASON field encoding (§9.1.4)
//
// §9.1.4 REASON:
//   0b00 = stage-1 / config fault  (s2=false)
//   0b01 = stage-2 during CD fetch (s2=true, event_class=0 CD)
//   0b10 = stage-2 during TT walk  (s2=true, event_class=1 TTD)
//   0b11 = stage-2 on IPA input    (s2=true, event_class=2 IN)
//
// SW model faults originate from input address (event_class=2 IN), so a stage-2
// IPA fault has s2=true, event_class=2 → REASON = 2 + 1 = 3 = 0b11.
//
// BEFORE FIX: reason = if s2 { 1 } else { 0 }  → always 0b01 for any stage-2 fault.
// AFTER FIX:  reason = if s2 { event_class + 1 } else { 0 } → 0b11 for IN class.
// ============================================================================

/// NEW-GAP-A Baseline: Stage-1-only fault → REASON=0b00.
///
/// Setup: Stage-1-only stream, no page mapped.
/// gatos_translate on unmapped IOVA → F_TRANSLATION, s2=false → REASON=0.
/// This should pass before and after the fix (regression guard).
#[test]
fn new_gap_a_stage1_fault_reason_is_0b00() {
    let smmu = SMMU::new();
    enable_smmu(&smmu);

    let stream_id = sid(0xB0);
    let cfg = StreamConfig::builder()
        .stage1_enabled(true)
        .stage2_enabled(false)
        .translation_enabled(true)
        .fault_mode(FaultMode::Terminate)
        .t0sz(0) // no VA range restriction
        .build()
        .unwrap();
    smmu.configure_stream(stream_id, cfg).unwrap();
    smmu.create_pasid(stream_id, pasid(0)).unwrap();
    // No page mapped → F_TRANSLATION on any IOVA.

    let par = smmu.gatos_translate(
        stream_id,
        pasid(0),
        iova(0x5000),
        AccessType::Read,
        SecurityState::NonSecure,
    );

    assert_eq!(par & 1, 1, "GATOS_PAR bit 0 must be 1 (FAULT)");
    let reason = extract_reason(par);
    assert_eq!(
        reason, 0,
        "NEW-GAP-A: stage-1 fault must produce REASON=0b00; got {reason}"
    );
}

/// NEW-GAP-A: Stage-2 IPA fault (unmapped IPA) → REASON=0b11.
///
/// Setup: Two-stage stream. Stage-1 maps IOVA=0x1000 → IPA=0x8000_0000.
/// Stage-2 has no mapping for IPA=0x8000_0000.
/// gatos_translate → stage-2 F_TRANSLATION with s2=true, event_class=2 (IN).
/// REASON = event_class + 1 = 3 = 0b11.
///
/// BEFORE FIX: REASON=1 (0b01) — wrong, uses `if s2 { 1 } else { 0 }`.
/// AFTER FIX:  REASON=3 (0b11) — correct, uses `if s2 { event_class + 1 } else { 0 }`.
#[test]
fn new_gap_a_stage2_ipa_fault_reason_is_0b11() {
    let smmu = SMMU::new();
    enable_smmu(&smmu);

    let stream_id = sid(0xB1);
    setup_two_stage_stream(&smmu, stream_id);
    map_stage1_page(&smmu, stream_id, 0x1000, 0x8000_0000);

    // gatosTranslate: stage-1 succeeds (IPA=0x8000_0000),
    // stage-2 fails (no mapping for IPA) → FAULT=1.
    let par = smmu.gatos_translate(
        stream_id,
        pasid(0),
        iova(0x1000),
        AccessType::Read,
        SecurityState::NonSecure,
    );

    assert_eq!(par & 1, 1, "GATOS_PAR bit 0 must be 1 (FAULT)");

    let reason = extract_reason(par);
    assert_eq!(
        reason, 3,
        "NEW-GAP-A: stage-2 IPA fault (IN class) must produce REASON=0b11 (3); \
         got {reason}. Before fix this was 0b01."
    );

    let fc = extract_faultcode(par);
    assert_eq!(
        fc, 0x10,
        "FAULTCODE must be 0x10 (F_TRANSLATION) for unmapped IPA; got 0x{fc:02x}"
    );
}

// ============================================================================
// NEW-GAP-I: GATOS_PAR FADDR[55:12] populated on stage-2 fault (§9.1.4)
//
// §9.1.4 Table row (TYPE=stage-1-and-2, REASON=0b11 S2 IN):
//   FADDR = "IPA input to stage 2 (stage 1 output)"
//
// When s2=true (any stage-2 fault), GATOS_PAR bits[55:12] must carry the
// page-aligned IPA (ev.ipa & 0x00FF_FFFF_FFFF_F000).
// For REASON=0b00 (stage-1/config fault, s2=false), FADDR must be 0.
//
// BEFORE FIX: par = 1 | (reason<<1) | (faultcode<<4) — FADDR always 0.
// AFTER FIX:  par |= (ipa & 0x00FF_FFFF_FFFF_F000) when s2=true.
// ============================================================================

/// NEW-GAP-I: Stage-2 IPA fault → FADDR[55:12] = page-aligned IPA.
///
/// IPA = 0x8000_1000 (4K-aligned).  After the fix, bits[55:12] of par
/// must equal 0x8000_1000.
///
/// BEFORE FIX: FADDR=0.
/// AFTER FIX:  FADDR=0x8000_1000.
#[test]
fn new_gap_i_gatos_par_faddr_set_to_faulting_ipa() {
    let smmu = SMMU::new();
    enable_smmu(&smmu);

    let stream_id = sid(0xB2);
    setup_two_stage_stream(&smmu, stream_id);
    map_stage1_page(&smmu, stream_id, 0x4000, 0x8000_1000);

    let par = smmu.gatos_translate(
        stream_id,
        pasid(0),
        iova(0x4000),
        AccessType::Read,
        SecurityState::NonSecure,
    );

    assert_eq!(par & 1, 1, "GATOS_PAR bit 0 must be 1 (FAULT)");
    assert_eq!(
        extract_reason(par),
        3,
        "REASON must be 0b11 (stage-2 IPA fault)"
    );

    let faddr = par & 0x00FF_FFFF_FFFF_F000_u64;
    assert_eq!(
        faddr,
        0x8000_1000_u64,
        "NEW-GAP-I: FADDR[55:12] must equal faulting IPA 0x8000_1000; \
         got 0x{faddr:016x}. Before fix FADDR was always 0."
    );
}

/// NEW-GAP-I Baseline: Stage-1-only fault → FADDR[55:12] must be 0.
///
/// REASON=0b00 → FADDR=0 per §9.1.4 table. Regression guard.
#[test]
fn new_gap_i_gatos_par_faddr_zero_for_stage1_fault() {
    let smmu = SMMU::new();
    enable_smmu(&smmu);

    let stream_id = sid(0xB3);
    let cfg = StreamConfig::builder()
        .stage1_enabled(true)
        .stage2_enabled(false)
        .translation_enabled(true)
        .fault_mode(FaultMode::Terminate)
        .t0sz(0)
        .build()
        .unwrap();
    smmu.configure_stream(stream_id, cfg).unwrap();
    smmu.create_pasid(stream_id, pasid(0)).unwrap();

    let par = smmu.gatos_translate(
        stream_id,
        pasid(0),
        iova(0x6000),
        AccessType::Read,
        SecurityState::NonSecure,
    );

    assert_eq!(par & 1, 1, "FAULT bit must be set");
    assert_eq!(extract_reason(par), 0, "REASON must be 0b00 for stage-1 fault");

    let faddr = par & 0x00FF_FFFF_FFFF_F000_u64;
    assert_eq!(
        faddr, 0,
        "NEW-GAP-I: FADDR must be 0 for stage-1 fault; got 0x{faddr:016x}"
    );
}
